#!/bin/bash
# ============================================================================
# BUILD SCRIPT: Combines modular source files into a single index.html
# ============================================================================
#
# This script takes the development structure:
#   - index-dev.html (references external files)
#   - css/styles.css
#   - js/*.js (multiple modules)
#
# And produces a single, self-contained index.html for deployment.
#
# Usage: ./build.sh
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

OUTPUT_FILE="index.html"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Building index.html from modular sources...${NC}"

# Check that all required files exist
REQUIRED_FILES=(
    "index-dev.html"
    "css/styles.css"
    "js/event-bus.js"
    "js/store.js"
    "js/route-manager.js"
    "js/storage-manager.js"
    "js/timeline.js"
    "js/components.js"
    "js/data.js"
    "js/stick-scene-player.js"
    "js/scene-manager.js"
    "js/file-api.js"
    "js/adventure-manager.js"
    "js/adventure-player.js"
    "js/adventure-tree-editor.js"
    "js/adventure-publisher.js"
    "js/chat-window.js"
    "js/planning-controller.js"
    "js/stage-controller.js"
    "js/implementation-controller.js"
    "js/testing-controller.js"
    "js/ui.js"
    "js/scene-studio.js"
    "js/main.js"
)

for file in "${REQUIRED_FILES[@]}"; do
    if [[ ! -f "$file" ]]; then
        echo -e "${RED}ERROR: Missing required file: $file${NC}"
        exit 1
    fi
done

# Start building the output
cat > "$OUTPUT_FILE" << 'HEADER'
<!DOCTYPE html>
<!--
================================================================================
    AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
================================================================================

    This file is automatically generated by build.sh from the modular source
    files in the css/ and js/ directories.

    To make changes:
    1. Edit the source files in css/ and js/
    2. Edit index-dev.html for HTML structure changes
    3. Run ./build.sh to regenerate this file

    Source files:
    - index-dev.html     (HTML structure)
    - css/styles.css     (Stylesheet)
    - js/event-bus.js    (EventBus pub/sub system)
    - js/store.js        (State management)
    - js/route-manager.js (URL routing)
    - js/storage-manager.js (localStorage persistence)
    - js/timeline.js     (Animation sequencer)
    - js/components.js   (Component registry)
    - js/data.js         (Data configurations)
    - js/stick-scene-player.js (Scene player engine)
    - js/scene-manager.js (Scene management)
    - js/stage-controller.js        (Stage transitions)
    - js/implementation-controller.js (Implementation stage)
    - js/testing-controller.js      (Testing stage)
    - js/chat-window.js  (ChatWindow component)
    - js/ui.js           (UI initialization)
    - js/main.js         (Entry point)

    Last generated: TIMESTAMP_PLACEHOLDER
================================================================================
-->
HEADER

# Replace timestamp placeholder
sed -i '' "s/TIMESTAMP_PLACEHOLDER/$(date '+%Y-%m-%d %H:%M:%S')/" "$OUTPUT_FILE"

# Extract and write the head section with inlined CSS
cat >> "$OUTPUT_FILE" << 'HEAD_START'
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Effortless Visualizer V3</title>
  <style>
HEAD_START

# Inline the CSS
cat "css/styles.css" >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'HEAD_END'
  </style>
</head>
HEAD_END

# Extract the body content from index-dev.html (everything between <body> and the script tags)
# We use sed to extract just the HTML body content, excluding the script tags
sed -n '/<body>/,/<script/{ /<body>/d; /<script/d; p; }' index-dev.html >> "$OUTPUT_FILE"

# Add the combined JavaScript
cat >> "$OUTPUT_FILE" << 'SCRIPT_START'
<script>
SCRIPT_START

# Concatenate all JS files in dependency order
JS_FILES=(
    "js/event-bus.js"
    "js/store.js"
    "js/route-manager.js"
    "js/storage-manager.js"
    "js/timeline.js"
    "js/components.js"
    "js/data.js"
    "js/stick-scene-player.js"
    "js/scene-manager.js"
    "js/file-api.js"
    "js/adventure-manager.js"
    "js/adventure-player.js"
    "js/adventure-tree-editor.js"
    "js/adventure-publisher.js"
    "js/chat-window.js"
    "js/planning-controller.js"
    "js/stage-controller.js"
    "js/implementation-controller.js"
    "js/testing-controller.js"
    "js/ui.js"
    "js/scene-studio.js"
    "js/main.js"
)

for js_file in "${JS_FILES[@]}"; do
    echo "" >> "$OUTPUT_FILE"
    echo "// ============================================================================" >> "$OUTPUT_FILE"
    echo "// SOURCE: $js_file" >> "$OUTPUT_FILE"
    echo "// ============================================================================" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    cat "$js_file" >> "$OUTPUT_FILE"
done

# Close the script and HTML
cat >> "$OUTPUT_FILE" << 'SCRIPT_END'

</script>

</body>
</html>
SCRIPT_END

# Calculate file sizes for reporting
DEV_SIZE=$(wc -c < index-dev.html)
CSS_SIZE=$(wc -c < css/styles.css)
JS_SIZE=0
for js_file in "${JS_FILES[@]}"; do
    size=$(wc -c < "$js_file")
    JS_SIZE=$((JS_SIZE + size))
done
TOTAL_SOURCE=$((DEV_SIZE + CSS_SIZE + JS_SIZE))
OUTPUT_SIZE=$(wc -c < "$OUTPUT_FILE")

echo -e "${GREEN}Build complete!${NC}"
echo ""
echo "Source files:"
echo "  - index-dev.html: $(printf "%'d" $DEV_SIZE) bytes"
echo "  - css/styles.css: $(printf "%'d" $CSS_SIZE) bytes"
echo "  - js/*.js (18 files): $(printf "%'d" $JS_SIZE) bytes"
echo "  - Total source: $(printf "%'d" $TOTAL_SOURCE) bytes"
echo ""
echo "Output:"
echo "  - index.html: $(printf "%'d" $OUTPUT_SIZE) bytes"
echo ""
echo -e "${YELLOW}Remember: Edit source files, not index.html!${NC}"
