-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 4
-- Total Raw Fields: 35
-- ============================================================================

-- ============================================================================
-- DROP SPECIFIC OBJECTS - Only dropping objects that will be recreated
-- ============================================================================

-- Drop functions (order: first, because views depend on them)
DROP FUNCTION IF EXISTS calc_language_candidates_has_grammar(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_language_candidates_is_description_of(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_language_candidates_is_open_closed_world_conflicted(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_language_candidates_predicted_answer(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_language_candidates_prediction_fail(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_language_candidates_prediction_predicates(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_language_candidates_question(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_language_candidates_relationship_to_concept(TEXT) CASCADE;

-- Drop views (order: second, because they depend on tables)
DROP VIEW IF EXISTS vw_erb_customizations CASCADE;
DROP VIEW IF EXISTS vw_is_everything_a_language CASCADE;
DROP VIEW IF EXISTS vw_language_candidates CASCADE;
DROP VIEW IF EXISTS vw_name CASCADE;

-- Drop tables (order: last, after dependent objects are removed)
DROP TABLE IF EXISTS erb_customizations CASCADE;
DROP TABLE IF EXISTS is_everything_a_language CASCADE;
DROP TABLE IF EXISTS language_candidates CASCADE;
DROP TABLE IF EXISTS name CASCADE;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

CREATE TABLE name (
);

CREATE TABLE language_candidates (
  language_candidate_id               TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  is_language                         BOOLEAN             ,
  has_syntax                          BOOLEAN             ,
  can_be_held                         BOOLEAN             ,
  category                            TEXT                ,
  has_identity                        BOOLEAN             ,
  is_parsed                           BOOLEAN             ,
  resolves_to_an_ast                  BOOLEAN             ,
  has_linear_decoding_pressure        BOOLEAN             ,
  is_stable_ontology_reference        BOOLEAN             ,
  is_live_ontology_editor             BOOLEAN             ,
  is_open_world                       BOOLEAN             ,
  is_closed_world                     BOOLEAN             ,
  distance_from_concept               INTEGER             ,
  dimensionality_while_editing        TEXT                ,
  model_object_facility_layer         TEXT                ,
  sort_order                          INTEGER             
);

CREATE TABLE is_everything_a_language (
  is_everything_a_language_id         TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  argument_name                       TEXT                ,
  argument_category                   TEXT                ,
  step_type                           TEXT                ,
  statement                           TEXT                ,
  formalization                       TEXT                ,
  related_candidate_name              TEXT                ,
  related_candidate_id                TEXT                ,
  evidence_from_rulebook              TEXT                ,
  notes                               TEXT                
);

CREATE TABLE erb_customizations (
  erb_customization_id                TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  title                               TEXT                ,
  sql_code                            TEXT                ,
  sql_target                          TEXT                ,
  customization_type                  TEXT                
);

