-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 4
-- ============================================================================

CREATE OR REPLACE VIEW vw_language_candidates WITH (security_invoker = ON) AS
SELECT
  t.language_candidate_id,
  t.name,
  t.is_language,
  calc_language_candidates_has_grammar(t.language_candidate_id) AS has_grammar,
  t.has_syntax,
  t.can_be_held,
  calc_language_candidates_question(t.language_candidate_id) AS question,
  calc_language_candidates_predicted_answer(t.language_candidate_id) AS predicted_answer,
  calc_language_candidates_prediction_predicates(t.language_candidate_id) AS prediction_predicates,
  calc_language_candidates_prediction_fail(t.language_candidate_id) AS prediction_fail,
  t.category,
  t.has_identity,
  t.is_parsed,
  t.resolves_to_an_ast,
  t.has_linear_decoding_pressure,
  t.is_stable_ontology_reference,
  t.is_live_ontology_editor,
  t.is_open_world,
  t.is_closed_world,
  calc_language_candidates_is_description_of(t.language_candidate_id) AS is_description_of,
  t.distance_from_concept,
  calc_language_candidates_is_open_closed_world_conflicted(t.language_candidate_id) AS is_open_closed_world_conflicted,
  t.dimensionality_while_editing,
  calc_language_candidates_relationship_to_concept(t.language_candidate_id) AS relationship_to_concept,
  t.model_object_facility_layer,
  t.sort_order
FROM language_candidates t;

CREATE OR REPLACE VIEW vw_is_everything_a_language WITH (security_invoker = ON) AS
SELECT
  t.is_everything_a_language_id,
  t.name,
  t.argument_name,
  t.argument_category,
  t.step_type,
  t.statement,
  t.formalization,
  t.related_candidate_name,
  t.related_candidate_id,
  t.evidence_from_rulebook,
  t.notes
FROM is_everything_a_language t;

CREATE OR REPLACE VIEW vw_erb_customizations WITH (security_invoker = ON) AS
SELECT
  t.erb_customization_id,
  t.name,
  t.title,
  t.sql_code,
  t.sql_target,
  t.customization_type
FROM erb_customizations t;

