-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('english', 'English', TRUE, TRUE, FALSE, 'Natural Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, 2, 'OneDimensionalSymbolic', 'M1', 1);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('a-coffee-mug', 'A Coffee Mug', FALSE, FALSE, TRUE, 'Physical Object', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 1, 'N/A', 'NA', 2);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('spoken-words', 'Spoken Words', TRUE, TRUE, FALSE, 'Natural Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, 2, 'OneDimensionalSymbolic', 'M1', 3);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('a-game-of-fortnite', 'A Game of Fortnite', FALSE, FALSE, FALSE, 'Running Software', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 1, 'MultiDimensionalNonSymbolic', 'M4', 4);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('sign-language', 'Sign Language', TRUE, TRUE, FALSE, 'Natural Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, 2, 'OneDimensionalSymbolic', 'M1', 5);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('editing-airtable-base', 'Editing Airtable Base', FALSE, FALSE, FALSE, 'Running Software', TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, 2, 'MultiDimensionalNonSymbolic', 'M4', 6);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('math', 'Math', TRUE, TRUE, FALSE, 'Formal Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, 2, 'OneDimensionalSymbolic', 'M1', 7);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('falsifier-a', 'Falsifier A', TRUE, FALSE, TRUE, 'MISSING: Have you seen this Language?', TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, 1, 'N/A', 'NA', 8);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('falsifier-b', 'Falsifier B', FALSE, TRUE, FALSE, 'MISSING: Have you seen this Language?', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, 2, 'N/A', 'M1', 9);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('a-smartphone', 'A Smartphone', FALSE, FALSE, TRUE, 'Physical Object', TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, 1, 'N/A', 'NA', 10);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('python', 'Python', TRUE, TRUE, FALSE, 'Formal Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, 2, 'OneDimensionalSymbolic', 'M1', 11);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('a-running-app', 'A Running App ', FALSE, FALSE, FALSE, 'Running Software', TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, 1, 'MultiDimensionalNonSymbolic', 'M4', 12);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('an-xlsx-doc', 'An XLSX Doc', TRUE, TRUE, FALSE, 'Formal Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, 2, 'OneDimensionalSymbolic', 'M2', 13);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('xlsx-editing', 'XLSX - Editing', FALSE, FALSE, FALSE, 'Running Software', FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, 1, 'MultiDimensionalNonSymbolic', 'M4', 14);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('an-docx-doc', 'An DOCX Doc', TRUE, TRUE, FALSE, 'Formal Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, 2, 'OneDimensionalSymbolic', 'M2', 15);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('docx-editing', 'DOCX - Editing', FALSE, FALSE, FALSE, 'Running Software', FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 1, 'MultiDimensionalNonSymbolic', 'M4', 16);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('owl-rdf-graphql-generally', 'OWL/RDF/GraphQL/... generally', TRUE, TRUE, FALSE, 'Natural Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, 2, 'OneDimensionalSymbolic', 'M2', 17);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('a-thunderstorm', 'A Thunderstorm', FALSE, FALSE, TRUE, 'Physical event', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 1, 'N/A', 'NA', 18);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('a-uml-file', 'A UML File', TRUE, TRUE, FALSE, 'Formal Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, 2, 'OneDimensionalSymbolic', 'M2', 23);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('the-mona-lisa', 'The Mona Lisa', FALSE, FALSE, TRUE, 'Physical Object', TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 1, 'N/A', 'NA', 20);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('binary-code', 'Binary Code', TRUE, TRUE, FALSE, 'Formal Language', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, 2, 'OneDimensionalSymbolic', 'M2', 21);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('running-calculator-app', 'Running Calculator App', FALSE, FALSE, FALSE, 'Running Software', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 1, 'MultiDimensionalNonSymbolic', 'M1', 22);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('owa-cwa-falsifier', 'OWA & CWA Falsifier', TRUE, TRUE, FALSE, 'MISSING: Have you seen this Language?', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, 2, 'OneDimensionalSymbolic', 'M1', 23);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('honeybee-waggle-dance', 'Honeybee Waggle Dance', TRUE, TRUE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('vervet-monkey-alarm-calls', 'Vervet Monkey Alarm Calls', FALSE, FALSE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('songbird-song-learned-dialects', 'Songbird Song (learned dialects)', TRUE, TRUE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('killer-whale-pod-dialects', 'Killer Whale Pod Dialects', FALSE, FALSE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('dolphin-signature-whistles', 'Dolphin Signature Whistles', FALSE, FALSE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('ant-pheromone-trail-system', 'Ant Pheromone Trail System', FALSE, FALSE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('cuttlefish-chromatophore-displays', 'Cuttlefish Chromatophore Displays', TRUE, TRUE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('nicaraguan-sign-language-early-cohort', 'Nicaraguan Sign Language (early cohort)', TRUE, TRUE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('homesign-single-child', 'Homesign (single child)', TRUE, TRUE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO language_candidates (language_candidate_id, name, is_language, has_syntax, can_be_held, category, has_identity, is_parsed, resolves_to_an_ast, has_linear_decoding_pressure, is_stable_ontology_reference, is_live_ontology_editor, is_open_world, is_closed_world, distance_from_concept, dimensionality_while_editing, model_object_facility_layer, sort_order)
VALUES ('bonobo-lexigram-keyboard-communication', 'Bonobo/Lexigram Keyboard Communication', TRUE, TRUE, FALSE, 'Natural Language', FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 0, '', '', 0);

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-001', 'NEIAL-001', 'LanguageCanBeFormalized', 'Definition', 'Motivation', 'To avoid the slogan ''Everything is a language'', treat ''language'' as a typed construct defined by testable properties (syntax, parsing, linear decoding pressure, and descriptor-role).', '', '', '', '', 'This keeps ''can be interpreted'' separate from ''is a language system''.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-002', 'NEIAL-002', 'LanguageCanBeFormalized', 'Definition', 'PredicateSet', 'Use the repo predicates: HasSyntax, RequiresParsing, HasLinearDecodingPressure, StableOntologyReference (spelled IsOngologyDescriptor in the dataset), plus auxiliary checks like CanBeHeld and HasIdentity.', 'Predicates: Syntax(x), Parse(x), SerializeMeaning(x), OntDesc(x), Tangible(x)', '', '', '', 'We preserve the dataset''s field name even when misspelled to match the generated schema.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-003', 'NEIAL-003', 'LanguageCanBeFormalized', 'Definition', 'Definition', 'Operational definition: an item x counts as a Language if it has syntax, requires parsing, serializes meaning, and functions as an ontology/descriptor system.', 'Language(x) := HasSyntax(x) ∧ RequiresParsing(x) ∧ HasLinearDecodingPressure(x) ∧ StableOntologyReference(x)', '', '', '', 'This is a deliberately ''strong'' definition: it matches formal languages and many natural language representations.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-004', 'NEIAL-004', 'LanguageCanBeFormalized', 'Premise', 'Witness', 'There exists at least one clear witness that satisfies the operational definition: English.', '∃x (x=English ∧ Language(x))', 'English', 'english', 'HasSyntax=True; RequiresParsing=True; HasLinearDecodingPressure=True; IsOngologyDescriptor=True; CanBeHeld=False; HasIdentity=False; DistanceFromConcept=2; Category=Natural Language', 'If any predicate is false in your current dataset for this witness, adjust the candidate record or relax the definition.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-005', 'NEIAL-005', 'LanguageCanBeFormalized', 'Premise', 'Witness', 'There exists at least one clear witness that satisfies the operational definition: Python.', '∃x (x=Python ∧ Language(x))', 'Python', 'python', 'HasSyntax=True; RequiresParsing=True; HasLinearDecodingPressure=True; IsOngologyDescriptor=True; CanBeHeld=False; HasIdentity=False; DistanceFromConcept=2; Category=Formal Language', 'If any predicate is false in your current dataset for this witness, adjust the candidate record or relax the definition.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-006', 'NEIAL-006', 'LanguageCanBeFormalized', 'Conclusion', 'Conclusion', 'Therefore, ''language'' can be formalized as a computable classification boundary over explicit predicates.', '(Definition ∧ Witnesses) ⇒ Formalizable(Language)', '', '', '', 'This is the concession: language is formalizable (at least operationally).');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-007', 'NEIAL-007', 'NotEverythingIsALanguage', 'Premise', 'Entailment', 'If Language(x) is defined by necessary conditions, then any x that fails at least one condition is not a language.', '∀x (¬(HasSyntax(x) ∧ RequiresParsing(x) ∧ HasLinearDecodingPressure(x) ∧ StableOntologyReference(x)) → ¬Language(x))', '', '', '', 'This is the standard move: a definition implies exclusions.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-008', 'NEIAL-008', 'NotEverythingIsALanguage', 'Example', 'Counterexample', 'Counterexample: a chair can be interpreted as a sign (status, design, function), but it does not constitute a language system under the operational definition.', '¬Language(Chair)', 'A Chair', '', '', 'This separates semiotic availability (can signify) from linguistic structure (has syntax/parsing/serialized meaning).');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-009', 'NEIAL-009', 'NotEverythingIsALanguage', 'Example', 'NonLanguageExample', 'Non-language example: A Thunderstorm can be meaningful, but meaning here is not generated by an explicit syntax+parsing+serialization descriptor system.', '¬Language(A Thunderstorm)', 'A Thunderstorm', 'a-thunderstorm', 'HasSyntax=False; RequiresParsing=True; HasLinearDecodingPressure=False; IsOngologyDescriptor=False; CanBeHeld=False; HasIdentity=True; DistanceFromConcept=1; Category=Physical event', 'These are strong candidates for ''sign vehicles'' rather than ''languages''.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-010', 'NEIAL-010', 'NotEverythingIsALanguage', 'Example', 'NonLanguageExample', 'Non-language example: A Coffee Mug can be meaningful, but meaning here is not generated by an explicit syntax+parsing+serialization descriptor system.', '¬Language(A Coffee Mug)', 'A Coffee Mug', 'a-coffee-mug', 'HasSyntax=False; RequiresParsing=False; HasLinearDecodingPressure=False; IsOngologyDescriptor=False; CanBeHeld=True; HasIdentity=True; DistanceFromConcept=1; Category=Physical Object', 'These are strong candidates for ''sign vehicles'' rather than ''languages''.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-011', 'NEIAL-011', 'NotEverythingIsALanguage', 'Example', 'NonLanguageExample', 'Non-language example: The Mona Lisa can be meaningful, but meaning here is not generated by an explicit syntax+parsing+serialization descriptor system.', '¬Language(The Mona Lisa)', 'The Mona Lisa', 'the-mona-lisa', 'HasSyntax=False; RequiresParsing=False; HasLinearDecodingPressure=False; IsOngologyDescriptor=True; CanBeHeld=True; HasIdentity=True; DistanceFromConcept=1; Category=Physical Object', 'These are strong candidates for ''sign vehicles'' rather than ''languages''.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-012', 'NEIAL-012', 'NotEverythingIsALanguage', 'Observation', 'FuzzyBoundary', 'Fuzzy case: A Running App often contains embedded languages (code, UI grammars), but as an executing/interactive process it behaves like a dynamic system rather than a static serialized language artifact.', 'Borderline(A Running App): may contain ∃y Language(y) but ¬Language(A Running App) under static-serialization criteria', 'A Running App', '', '', 'This is where traditional semiotics'' ''anything is a sign'' doesn’t neatly distinguish: (1) language-as-system vs (2) meaning-making interactive processes.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-013', 'NEIAL-013', 'NotEverythingIsALanguage', 'Observation', 'FuzzyBoundary', 'Fuzzy case: Running Calculator App often contains embedded languages (code, UI grammars), but as an executing/interactive process it behaves like a dynamic system rather than a static serialized language artifact.', 'Borderline(Running Calculator App): may contain ∃y Language(y) but ¬Language(Running Calculator App) under static-serialization criteria', 'Running Calculator App', 'running-calculator-app', 'HasSyntax=False; RequiresParsing=True; HasLinearDecodingPressure=False; IsOngologyDescriptor=False; CanBeHeld=False; HasIdentity=True; DistanceFromConcept=1; Category=Running Software', 'This is where traditional semiotics'' ''anything is a sign'' doesn’t neatly distinguish: (1) language-as-system vs (2) meaning-making interactive processes.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-014', 'NEIAL-014', 'NotEverythingIsALanguage', 'Observation', 'FuzzyBoundary', 'Fuzzy case: A Game of Fortnite often contains embedded languages (code, UI grammars), but as an executing/interactive process it behaves like a dynamic system rather than a static serialized language artifact.', 'Borderline(A Game of Fortnite): may contain ∃y Language(y) but ¬Language(A Game of Fortnite) under static-serialization criteria', 'A Game of Fortnite', 'a-game-of-fortnite', 'HasSyntax=False; RequiresParsing=True; HasLinearDecodingPressure=False; IsOngologyDescriptor=False; CanBeHeld=False; HasIdentity=True; DistanceFromConcept=1; Category=Running Software', 'This is where traditional semiotics'' ''anything is a sign'' doesn’t neatly distinguish: (1) language-as-system vs (2) meaning-making interactive processes.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-015', 'NEIAL-015', 'NotEverythingIsALanguage', 'Definition', 'Refinement', 'Refinement: distinguish LanguageSystem (syntax/parsing/serialization descriptor) from SemioticProcess (interactive/dynamic meaning production) and from SignVehicle (object/phenomenon used as a sign).', 'Kinds: LanguageSystem(x) | SemioticProcess(x) | SignVehicle(x)', '', '', '', 'This gives you a place to put running apps and games without forcing ''language'' to swallow everything.');

INSERT INTO is_everything_a_language (is_everything_a_language_id, name, argument_name, argument_category, step_type, statement, formalization, related_candidate_name, related_candidate_id, evidence_from_rulebook, notes)
VALUES ('neial-016', 'NEIAL-016', 'NotEverythingIsALanguage', 'Conclusion', 'Conclusion', 'Given a formalizable definition of language, not everything is a language; some things are better treated as sign vehicles or semiotic processes, with running applications as a key fuzzy region that benefits from explicit modeling.', 'Formalizable(Language) ∧ ∃x ¬Language(x) ⇒ ¬(EverythingIsALanguage)', '', '', '', 'This is the repo''s thesis in one line.');

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('01b-customize-schema-sql', '01b-customize-schema.sql', 'Customize Schema', '-- ============================================================================
-- CUSTOMIZE SCHEMA - User-defined tables and schema modifications
-- ============================================================================
-- This file is for YOUR custom schema changes that should persist across
-- regeneration of the base ERB files.
--
-- USE THIS FILE FOR:
--   - Additional tables not defined in the rulebook
--   - Extra columns on existing tables (ALTER TABLE)
--   - Custom indexes for performance tuning
--   - Custom constraints or triggers
--
-- IMPORTANT:
--   - This file runs AFTER 01-drop-and-create-tables.sql
--   - The base tables already exist when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom schema changes go here:
', 'Postgres', 'Schema');

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('02b-customize-functions-sql', '02b-customize-functions.sql', 'Customize Functions', '-- Prediction Fail: Returns TRUE when predicted_answer doesn''t match is_language
DROP FUNCTION calc_language_candidates_question;

CREATE OR REPLACE FUNCTION public.calc_language_candidates_question(p_language_candidate_id text)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
AS $function$
BEGIN
  RETURN (''Is '' || (SELECT NULLIF(name, '''''''') FROM language_candidates WHERE language_candidate_id = p_language_candidate_id) || '' a language?'')::text;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calc_language_candidates_bio_hockett_score(p_language_candidate_id text)
 RETURNS integer
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
AS $function$
DECLARE
    candidate_record RECORD;
BEGIN
    -- Select the required attributes for the given language candidate ID
    SELECT bio_has_semanticity, bio_has_arbitrariness, bio_has_discreteness, 
           bio_has_duality_of_patterning, bio_has_productivity, 
           bio_has_displacement, bio_has_cultural_transmission, 
           bio_has_interchangeability, bio_has_feedback, 
           bio_has_broadcast_transmission, bio_has_rapid_fading
    INTO candidate_record
    FROM language_candidates
    WHERE language_candidate_id = p_language_candidate_id;

    -- Calculate and return the Hockett score by summing up the boolean attributes
    RETURN 
        COALESCE(candidate_record.bio_has_semanticity, FALSE)::int +
        COALESCE(candidate_record.bio_has_arbitrariness, FALSE)::int +
        COALESCE(candidate_record.bio_has_discreteness, FALSE)::int +
        COALESCE(candidate_record.bio_has_duality_of_patterning, FALSE)::int +
        COALESCE(candidate_record.bio_has_productivity, FALSE)::int +
        COALESCE(candidate_record.bio_has_displacement, FALSE)::int +
        COALESCE(candidate_record.bio_has_cultural_transmission, FALSE)::int +
        COALESCE(candidate_record.bio_has_interchangeability, FALSE)::int +
        COALESCE(candidate_record.bio_has_feedback, FALSE)::int +
        COALESCE(candidate_record.bio_has_broadcast_transmission, FALSE)::int +
        COALESCE(candidate_record.bio_has_rapid_fading, FALSE)::int;
END;
$function$;
', 'Postgres', 'Functions');

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('03b-customize-views-sql', '03b-customize-views.sql', 'Customize Views', '-- ============================================================================
-- CUSTOMIZE VIEWS - User-defined views and view extensions
-- ============================================================================
-- This file is for YOUR custom views that should persist across
-- regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER 03-create-views.sql
--   - All base vw_* views already exist when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom views go here:
', 'Postgres', 'Views');

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('04b-customize-rls-sql', '04b-customize-rls.sql', 'Customize Policies (RLS)', '-- ============================================================================
-- CUSTOMIZE POLICIES - User-defined Row Level Security policies
-- ============================================================================
-- This file is for YOUR custom RLS policies that should persist across
-- regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER 04-create-policies.sql
--   - Base RLS policies already exist when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom policies go here:
', 'Postgres', 'RLS');

INSERT INTO erb_customizations (erb_customization_id, name, title, sql_code, sql_target, customization_type)
VALUES ('05b-customize-data-sql', '05b-customize-data.sql', 'Customize Data (Seeds / Migrations)', '-- ============================================================================
-- CUSTOMIZE DATA - User-defined seed data and data migrations
-- ============================================================================
-- This file is for YOUR custom seed data that should persist across
-- regeneration of the base ERB files.
--
-- IMPORTANT:
--   - This file runs AFTER 05-insert-data.sql
--   - Base seed data already exists when this runs
--   - This file will NOT be overwritten by ERB regeneration
--
-- ============================================================================

-- Your custom data inserts go here:
', 'Postgres', 'Data');

